World wide web

diff --git a/0x10-https_ssl/0-world_wide_web b/0x10-https_ssl/0-world_wide_web
--- a/0x10-https_ssl/0-world_wide_web
+++ b/0x10-https_ssl/0-world_wide_web
@@ -1,16 +1,38 @@
 #!/usr/bin/env bash
 # Script that displays information about subdomains.
 
-func () {
-    if [ -n "$2" ]
-    then
-	dig "$2.$1" | grep -A1 'ANSWER SECTION:' | paste - - | awk -v sd="$2" '{print "The subdomain " sd " is a " $7 " record and points to " $8}'
-    else
-	dig "www.$1" | grep -A1 'ANSWER SECTION:' | paste - - | awk '{print "The subdomain www is a " $7 " record and points to " $8}'
-	dig "lb-01.$1" | grep -A1 'ANSWER SECTION:' | paste - - | awk '{print "The subdomain lb-01 is a " $7 " record and points to " $8}'
-	dig "web-01.$1" | grep -A1 'ANSWER SECTION:' | paste - - | awk '{print "The subdomain web-01 is a " $7 " record and points to " $8}'
-	dig "web-02.$1" | grep -A1 'ANSWER SECTION:' | paste - - | awk '{print "The subdomain web-02 is a " $7 " record and points to " $8}'
-    fi
+function get_dns_info() {
+        local domain="$1"
+        local subdomain="$2"
+        local dig_output
+
+        if [ -n "$subdomain" ]; then
+                dig_output=$(dig "$subdomain.$domain" +short)
+        else
+                dig_output=$(dig "www.$domain" +short)
+                dig_output+="\n$(dig "lb-01.$domain" +short)"
+                dig_output+="\n$(dig "web-01.$domain" +short)"
+                dig_output+="\n$(dig "web-02.$domain" +short)"
+        fi
+
+        if [ -z "$dig_output" ]; then
+                echo "Unable to retrieve DNS information for $subdomain.$domain"
+                return 1
+        fi
+
+        echo "$dig_output" | awk -v sd="$subdomain" '{print "The subdomain " sd " is a " "A" " record and points to " $1}'
 }
 
-func "$1" "$2"
+if [ -z "$1" ]; then
+        echo "Usage: $0 <domain name> [subdomain name]"
+        exit 1
+fi
+
+if [ -n "$2" ]; then
+        get_dns_info "$1" "$2"
+else
+        get_dns_info "$1" "www"
+        get_dns_info "$1" "lb-01"
+        get_dns_info "$1" "web-01"
+        get_dns_info "$1" "web-02"
+fi
